FROM mcr.microsoft.com/devcontainers/base:bionic

# Set working directory
# WORKDIR /home/

# Install NodeJS 12.11.x
# RUN curl -sL https://deb.nodesource.com/setup_12.x -o nodesource_setup.sh
# RUN sudo bash nodesource_setup.sh
# RUN sudo apt install nodejs -y

# Install Jest, Babel, and ESLint
# RUN npm install --save-dev jest
# RUN npm install --save-dev babel-jest @babel/core @babel/preset-env
# RUN npm install --save-dev eslint

# Install dependencies
# RUN npm install

# RUN npm audit fix